name: jessicamorganphotography
favicon: null
layout_spectrum: 1
typography_spectrum: 0.2696711455937475
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#483828'
    - '#867665'
    - '#cab9a9'
    - '#000000'
    - '#fffffe'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.6462574540637434
  rhythmicContrast: 0.09511381550692022
purpose: []
