name: jessicamorganphotography
favicon: null
layout_spectrum: 0.167122564278543
typography_spectrum: 0.2696711455937475
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.17046211753040552
  lightness: 0.3946671294979751
  saturation: 0.6462574540637434
  rhythmicContrast: 0.09511381550692022
purpose: []
