name: jessicamorganphotography
favicon: null
layout_spectrum: 0
typography_spectrum: 0.65692
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#483828'
    - '#867665'
    - '#cab9a9'
    - '#000000'
    - '#fffffe'
  brandStrength: 0.125
  lightness: 0.5
  saturation: 0.875
  rhythmicContrast: 0.09511381550692022
purpose: []
